"""Deterministic org-wide diagram rendering from the compiled interface and dependency indices
(design D3/D4; dependency-indexing capability extends this to render dependency edges alongside
interface edges — architecture-diagrams spec, "Org diagram document shape").

Pure function, same shape as ``docs.render_interface_docs()``: compiled indices in, org diagram
markdown out. No LLM involvement — the content is mechanically derived from the compiled indices'
``owner``/``producer``/``consumer`` data, so it can never disagree with the index that produced it
and is exempt from doc-drift checking by construction.

One ``## {repo}`` section per repo with at least one interface or external dependency
(alphabetical), each with a small relationship graph (this repo as center node, one node per
interface resource and related repo; interface edges dashed, dependency edges solid, and a
dependency linked to an interface via ``panopticon-dependency-of`` collapsed into one thick/double
edge representing both — architecture-diagrams spec, "Linked dependency and interface edges
deduplicate") and a table of that repo's interfaces and external dependencies. Single-repository
interfaces remain visible; internal-only dependencies do not create a section.
"""

import re
from pathlib import Path

from .config import DEFAULT_DIAGRAM_FORMAT
from .index import CONFLICT_REASON_POTENTIAL_NAME_COLLISION, MULTIPLE_INTERFACE_TYPES

# Instance repo root, distinct from docs/{repo}/architecture.md (each child repo's own copy).
ORG_DIAGRAM_PATH = Path("docs") / "architecture.md"

_GENERATED_HEADER = (
    "<!-- Generated by panopticon.diagrams from the compiled interface and dependency indices.\n"
    "     Do not edit by hand: rebuilt automatically on every merge to a child repo's default branch. -->"
)

_MERMAID_ID_RE = re.compile(r"[^A-Za-z0-9_]")

# Empty-state placeholder (architecture-diagrams spec, "Org diagram renders an explicit
# empty-state placeholder"): shown before any child repo has merged an interface or cross-repo
# dependency. Six `?`-labeled nodes in a ring — deliberately uniform, unlike any real diagram, so
# it can never be mistaken for actual data.
#
# Relative to docs/architecture.md's own directory (docs/), not the instance repo root — same
# double-"docs/" pitfall as the child-repo navigation links above (see the architecture-diagrams
# spec's "Diagram navigation uses plain links" requirement): "docs/setup-guide.md" would resolve
# to the non-existent docs/docs/setup-guide.md.
_SETUP_GUIDE_LINK = "setup-guide.md#4-initialize-a-child-repo"
_HEXAGON_NODE_IDS = ("n1", "n2", "n3", "n4", "n5", "n6")


def _mermaid_id(repo):
    return "repo_" + _MERMAID_ID_RE.sub("_", repo)


def _empty_state_hexagon():
    """Six `?` nodes connected into a ring — the only implemented renderer is Mermaid (see
    render_org_diagram's docstring), so this always emits Mermaid graph syntax regardless of the
    caller's requested `fmt`, same as the rest of this module today."""
    lines = ["graph LR"] + [f'    {node}(("?"))' for node in _HEXAGON_NODE_IDS]
    for a, b in zip(_HEXAGON_NODE_IDS, _HEXAGON_NODE_IDS[1:] + _HEXAGON_NODE_IDS[:1]):
        lines.append(f"    {a} --- {b}")
    return "\n".join(lines)


def repo_set(entry):
    """The union of repo names in one interface/dependency entry's owner/producer/consumer
    (used to identify external dependency relationships); the same field shape serves both
    schemas."""
    repos = set()
    owner = entry.get("owner")
    if owner:
        repos.add(owner["repo"])
    for role in ("producer", "consumer"):
        repos.update(robj["repo"] for robj in entry[role])
    return repos


def _other_repo_role(entry, other_repo):
    """`other_repo`'s role(s) for this entry — owner, producer, and/or consumer."""
    roles = []
    owner = entry.get("owner")
    if owner and owner["repo"] == other_repo:
        roles.append("owner")
    if any(robj["repo"] == other_repo for robj in entry["producer"]):
        roles.append("producer")
    if any(robj["repo"] == other_repo for robj in entry["consumer"]):
        roles.append("consumer")
    return roles


def _rows_for_index(doc, key, type_field, kind, repo, include_internal=False):
    """Rows for `repo` from one compiled index, optionally retaining local-only resources."""
    rows = []
    for name in sorted(doc.get(key, {})):
        for entry in doc[key][name]:
            repos = repo_set(entry)
            if repo not in repos or (len(repos) <= 1 and not include_internal):
                continue
            produces = any(robj["repo"] == repo for robj in entry["producer"])
            consumes = any(robj["repo"] == repo for robj in entry["consumer"])
            direction = [d for d, flag in (("produces", produces), ("consumes", consumes)) if flag]
            if not direction:
                # repo owns this entry but neither produces nor consumes it itself.
                direction = ["owns"]
            others = sorted(repos - {repo}) or [None]
            for other in others:
                rows.append(
                    {
                        "kind": kind,
                        "name": name,
                        "type": entry[type_field],
                        "direction": "/".join(direction),
                        "produces": produces,
                        "consumes": consumes,
                        "other_repo": other,
                        "other_role": "/".join(_other_repo_role(entry, other)) if other else "—",
                        "links_to_interface": entry.get("links_to_interface"),
                    }
                )
    return rows


def _dedupe_linked_rows(rows):
    """Collapse a dependency row into its linked interface row when `links_to_interface` names an
    interface row relating the same two repos (architecture-diagrams spec, "Linked dependency and
    interface edges deduplicate") — never guessed, only when an explicit hint set the link."""
    interface_positions = {
        (r["name"], r["type"], r["other_repo"]): i
        for i, r in enumerate(rows)
        if r["kind"] == "interface"
    }
    consumed = set()
    merged_at = {}
    for i, row in enumerate(rows):
        if row["kind"] != "dependency" or not row.get("links_to_interface"):
            continue
        link = row["links_to_interface"]
        iface_idx = interface_positions.get((link["name"], link["type"], row["other_repo"]))
        if iface_idx is None or iface_idx in consumed:
            continue
        combined = dict(rows[iface_idx])
        combined["kind"] = "linked"
        combined["name"] = f"{rows[iface_idx]['name']} + {row['name']}"
        merged_at[i] = combined
        consumed.update((iface_idx, i))
    result = []
    for i, row in enumerate(rows):
        if i in merged_at:
            result.append(merged_at[i])
        elif i in consumed:
            continue
        else:
            result.append(row)
    return result


def relationships_for_repo(interfaces_compiled, repo, dependencies_compiled=None):
    """Interface and external-dependency rows for `repo`, combined into one list (deduplicated
    when a dependency is explicitly linked to an interface). Local-only interfaces are retained;
    local-only dependencies are excluded. `dependencies_compiled` defaults to empty — interface-only
    callers are unaffected."""
    exact_targets = set()
    name_targets = set()
    for conflict in interfaces_compiled.get("conflicts", []):
        if conflict["reason"] == CONFLICT_REASON_POTENTIAL_NAME_COLLISION:
            name_targets.add(conflict["name"])
        else:
            exact_targets.add((conflict["name"], conflict["type"]))
    rows = _rows_for_index(
        interfaces_compiled, "interfaces", "type", "interface", repo, include_internal=True
    )
    for row in rows:
        row["conflicted"] = (row["name"], row["type"]) in exact_targets or row["name"] in name_targets
    rows += _rows_for_index(dependencies_compiled or {}, "dependencies", "ecosystem", "dependency", repo)
    return _dedupe_linked_rows(rows)


def _mermaid_graph(repo, rows):
    lines = ["graph LR", f'    {_mermaid_id(repo)}["{repo}"]']
    seen = {repo}
    conflict_resources = set()
    resource_nodes = set()
    for row in rows:
        other = row["other_repo"]
        if other and other not in seen:
            lines.append(f'    {_mermaid_id(other)}["{other}"]')
            seen.add(other)
        # Visual distinction by kind (architecture-diagrams spec): dashed for interface, solid
        # for dependency, thick/double for a linked (deduplicated) pair.
        arrow = {"interface": "-.->", "dependency": "-->", "linked": "==>"}[row["kind"]]
        if row["kind"] != "dependency":
            resource = _mermaid_id(f"resource_{row['name']}_{row['type']}")
            if resource not in resource_nodes:
                lines.append(f'    {resource}["{row["name"]}"]')
                resource_nodes.add(resource)
            if row.get("conflicted") and resource not in conflict_resources:
                lines.append(f"    class {resource} conflictResource")
                conflict_resources.add(resource)
            if other is None:
                if row["consumes"] and not row["produces"]:
                    lines.append(f"    {resource} {arrow} {_mermaid_id(repo)}")
                else:
                    lines.append(f"    {_mermaid_id(repo)} {arrow} {resource}")
            elif row["consumes"] and not row["produces"]:
                lines += [
                    f"    {_mermaid_id(other)} {arrow} {resource}",
                    f"    {resource} {arrow} {_mermaid_id(repo)}",
                ]
            else:
                lines += [
                    f"    {_mermaid_id(repo)} {arrow} {resource}",
                    f"    {resource} {arrow} {_mermaid_id(other)}",
                ]
        elif row["consumes"] and not row["produces"]:
            lines.append(f"    {_mermaid_id(other)} {arrow}|{row['name']}| {_mermaid_id(repo)}")
        else:
            # produces (with or without also consuming), or owns-only: repo -> other.
            lines.append(f"    {_mermaid_id(repo)} {arrow}|{row['name']}| {_mermaid_id(other)}")
    if conflict_resources:
        lines.append("    classDef conflictResource fill:#fee2e2,stroke:#dc2626,color:#b91c1c,font-weight:bold")
    return "\n".join(lines)


_KIND_LABELS = {"interface": "interface", "dependency": "dependency", "linked": "interface + dependency"}


def _table(rows):
    lines = [
        "| Kind | Name | Type/Ecosystem | Direction | Other repo | Other repo's role |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        other = row["other_repo"]
        link = f"[{other}]({other}/architecture.md)" if other else "—"
        name = f"🔴 **`{row['name']}`**" if row.get("conflicted") else f"`{row['name']}`"
        lines.append(
            f"| {_KIND_LABELS[row['kind']]} | {name} | {row['type']} | {row['direction']} | "
            f"{link} | {row['other_role']} |"
        )
    return "\n".join(lines)


def render_org_diagram(interfaces_compiled, dependencies_compiled=None, diagram_format=None):
    """Deterministic org-diagram document (design D3/D4). `dependencies_compiled` defaults to
    empty (interface-only rendering, unchanged from before dependency-indexing existed).
    `diagram_format` tags each repo section's fenced graph block (default: DEFAULT_DIAGRAM_FORMAT)
    — callers are responsible for rejecting unsupported formats before calling this
    (config.require_supported_diagram_format); this function only renders Mermaid graph syntax,
    the only implemented renderer."""
    dependencies_compiled = dependencies_compiled or {}
    fmt = diagram_format or DEFAULT_DIAGRAM_FORMAT
    repos = sorted(
        {r for entries in interfaces_compiled.get("interfaces", {}).values() for entry in entries for r in repo_set(entry)}
        | {r for entries in dependencies_compiled.get("dependencies", {}).values() for entry in entries for r in repo_set(entry)}
    )
    lines = [_GENERATED_HEADER, "", "# Organization architecture", ""]
    conflicts = interfaces_compiled.get("conflicts", [])
    if conflicts:
        lines += ["## Detected interface conflicts", ""]
        for conflict in conflicts:
            type_label = "multiple types" if conflict["type"] == MULTIPLE_INTERFACE_TYPES else conflict["type"]
            repositories = ", ".join(f"`{claim['claimed_by']}`" for claim in conflict["claims"])
            lines.append(
                f"- **`{conflict['name']}` ({type_label})** — {conflict['reason']}: "
                f"{conflict['details']} (repositories: {repositories})"
            )
        lines.append("")
    any_section = False
    for repo in repos:
        rows = relationships_for_repo(interfaces_compiled, repo, dependencies_compiled)
        if not rows:
            continue
        any_section = True
        lines += [
            f"## {repo}",
            "",
            f"See this repo's own diagram: [{repo}/architecture.md]({repo}/architecture.md)",
            "",
            f"```{fmt}",
            _mermaid_graph(repo, rows),
            "```",
            "",
            _table(rows),
            "",
        ]
    if not any_section:
        lines += [
            f"No interfaces or external dependency relationships yet — see [initializing a child "
            f"repo]({_SETUP_GUIDE_LINK}).",
            "",
            f"```{fmt}",
            _empty_state_hexagon(),
            "```",
            "",
        ]
    return "\n".join(lines)


def write_org_diagram(instance_root, diagram_format=None):
    """Read both compiled indices fresh from `instance_root` (missing files treated as empty —
    e.g. a repo with no dependency shard yet) and write the combined org diagram. Reading from
    disk rather than accepting in-memory compiled docs lets either merge path
    (`merge.merge_into_instance`, `dependency_merge.merge_into_instance`) trigger the same
    rebuild and always render the other index's current state too, never a stale one."""
    from .dependencies import KIND_COMPILED as DEP_KIND_COMPILED
    from .dependencies import empty_index as empty_dependency_index
    from .dependencies import load_index as load_dependency_index
    from .index import KIND_COMPILED as IFACE_KIND_COMPILED
    from .index import empty_index as empty_interface_index
    from .index import load_index as load_interface_index
    from .merge import COMPILED_BASENAME as IFACE_COMPILED_BASENAME
    from .merge import INTERFACES_DIR
    from .dependency_merge import COMPILED_BASENAME as DEP_COMPILED_BASENAME
    from .dependency_merge import DEPENDENCIES_DIR

    instance_root = Path(instance_root)
    interfaces_path = instance_root / INTERFACES_DIR / IFACE_COMPILED_BASENAME
    dependencies_path = instance_root / DEPENDENCIES_DIR / DEP_COMPILED_BASENAME
    interfaces_compiled = (
        load_interface_index(interfaces_path, kind=IFACE_KIND_COMPILED)
        if interfaces_path.is_file()
        else empty_interface_index(IFACE_KIND_COMPILED)
    )
    dependencies_compiled = (
        load_dependency_index(dependencies_path, kind=DEP_KIND_COMPILED)
        if dependencies_path.is_file()
        else empty_dependency_index(DEP_KIND_COMPILED)
    )
    path = instance_root / ORG_DIAGRAM_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_org_diagram(interfaces_compiled, dependencies_compiled, diagram_format), encoding="utf-8"
    )
    return path
