"""Documentation tooling: deterministic interface-doc rendering, in-place regeneration, validation.

The four documentation layers (doc-generation spec) live in the repo's configured docs location:

- ``architecture.md`` — architecture overview (agent-written)
- ``components/<name>.md`` — per-component docs (agent-written, fixed template)
- ``interfaces.md`` — interface docs, **rendered deterministically from the local index** by this
  module so they can never disagree with it (never LLM prose)
- ``operations.md`` — operational docs (agent-written)

Agent-written layers are produced/updated through the panopticon-doc-generation skill; this
module owns everything deterministic: rendering ``interfaces.md``, pruning per-component docs for
deleted components (regeneration updates in place, no parallel copies), and validating that all
four layers exist (used by init and CI).
"""

import argparse
import sys
from pathlib import Path

from .index import KIND_LOCAL, load_index

ARCHITECTURE_DOC = "architecture.md"
COMPONENTS_DIR = "components"
INTERFACES_DOC = "interfaces.md"
OPERATIONS_DOC = "operations.md"

_GENERATED_HEADER = (
    "<!-- Generated by panopticon.docs from the local interface index. Do not edit by hand:\n"
    "     rerun `python3 -m panopticon.docs render --repo-name <repo>` after index changes. -->"
)


def render_interface_docs(index_doc, repo_name):
    """Deterministic markdown rendering of a local index (doc layer 3)."""
    lines = [_GENERATED_HEADER, "", f"# {repo_name} — interfaces", ""]
    interfaces = index_doc.get("interfaces", {})
    if not interfaces:
        lines += ["This repo declares no interfaces in its local index.", ""]
        return "\n".join(lines)
    for name in sorted(interfaces):
        for entry in interfaces[name]:
            lines.append(f"## `{name}` ({entry['type']})")
            lines.append("")
            owner = entry.get("owner")
            if owner:
                ours = " (this repo)" if owner["repo"] == repo_name else ""
                lines.append(f"- **Owner:** {owner['repo']} / {owner['component']}{ours}")
            else:
                lines.append("- **Owner:** unknown or manually created infrastructure")
            if entry.get("extracted_by") == "llm":
                lines.append("- **Provenance:** extracted by LLM (no deterministic parser yet)")
            for role, label in (("producer", "Produced by"), ("consumer", "Consumed by")):
                for repo_object in entry[role]:
                    files = ", ".join(f"`{f}`" for f in repo_object["source_files"])
                    lines.append(f"- **{label} this repo via:** {files}")
            lines.append("")
    return "\n".join(lines)


def write_interface_docs(index_doc, docs_root, repo_name):
    docs_root = Path(docs_root)
    docs_root.mkdir(parents=True, exist_ok=True)
    path = docs_root / INTERFACES_DOC
    path.write_text(render_interface_docs(index_doc, repo_name), encoding="utf-8")
    return path


def component_doc_names(docs_root):
    components_dir = Path(docs_root) / COMPONENTS_DIR
    if not components_dir.is_dir():
        return []
    return sorted(path.stem for path in components_dir.glob("*.md"))


def prune_component_docs(docs_root, current_components):
    """Remove per-component docs whose component no longer exists. Returns removed doc names."""
    components_dir = Path(docs_root) / COMPONENTS_DIR
    removed = []
    if not components_dir.is_dir():
        return removed
    keep = set(current_components)
    for path in sorted(components_dir.glob("*.md")):
        if path.stem not in keep:
            path.unlink()
            removed.append(path.stem)
    return removed


def regenerate(docs_root, index_doc, repo_name, current_components=None):
    """In-place regeneration of the deterministic layer: rewrite interfaces.md, prune components.

    Agent-written layers are regenerated by the doc-generation skill; this keeps the generated
    artifacts consistent with the index and the component set without creating parallel copies.
    """
    write_interface_docs(index_doc, docs_root, repo_name)
    removed = prune_component_docs(docs_root, current_components) if current_components is not None else []
    return {"interfaces_doc": str(Path(docs_root) / INTERFACES_DOC), "removed_components": removed}


def validate_docs(docs_root):
    """Check the four layers exist; returns a list of unmet requirements (empty when valid)."""
    docs_root = Path(docs_root)
    problems = []
    for doc, layer in (
        (ARCHITECTURE_DOC, "architecture overview"),
        (INTERFACES_DOC, "interface docs"),
        (OPERATIONS_DOC, "operational docs"),
    ):
        path = docs_root / doc
        if not path.is_file() or not path.read_text(encoding="utf-8").strip():
            problems.append(f"{layer} layer missing or empty: {path}")
    if not component_doc_names(docs_root):
        problems.append(f"per-component docs layer missing: no *.md files in {docs_root / COMPONENTS_DIR}/")
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description="Deterministic Panopticon doc tooling.")
    sub = parser.add_subparsers(dest="command", required=True)

    render = sub.add_parser("render", help="render interfaces.md from the local index")
    render.add_argument("--index", default="panopticon/index.json")
    render.add_argument("--docs-root", default="docs")
    render.add_argument("--repo-name", required=True)
    render.add_argument("--component", action="append", dest="components", default=None,
                        help="current component names; when given, stale component docs are pruned")

    validate = sub.add_parser("validate", help="check that all four documentation layers exist")
    validate.add_argument("--docs-root", default="docs")

    args = parser.parse_args(argv)
    if args.command == "render":
        index_doc = load_index(args.index, kind=KIND_LOCAL, repo=args.repo_name)
        result = regenerate(args.docs_root, index_doc, args.repo_name, args.components)
        print(f"wrote {result['interfaces_doc']}")
        for name in result["removed_components"]:
            print(f"removed stale component doc: {name}.md")
        return 0
    problems = validate_docs(args.docs_root)
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
